# ./docker-compose.yml
version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb_data_container:/data/db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  scrapper:
    network_mode: "host"
    build:
      dockerfile: ./Scrapper/Dockerfile
      context: .
    volumes:
      - img_dump:/Dataset/Scrapper/dump
    depends_on:
      - mongodb

  backend:
    network_mode: "host"
    build:
      dockerfile: ./Sanitizer/backend/Dockerfile
      context: .
    volumes:
      - img_dump:/Dataset/Scrapper/dump
    depends_on:
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  frontend:
    stdin_open: true
    network_mode: "host"
    build:
      dockerfile: ./Sanitizer/frontend/Dockerfile
      context: .
    depends_on:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
volumes:
  mongodb_data_container:
  img_dump:
