# ./docker-compose.yml
version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  scrapper:
    build:
      dockerfile: ./Scrapper/Dockerfile
      context: .
    volumes:
      - .:/Dataset

volumes:
    mongodb_data_container:
